[server]
headless = true
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#0F4C81"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0F172A"
font = "sans serif"
